import 'dart:ui';

import 'package:flutter/material.dart';

class AppColors {
  static final textColor = const Color(0xFFccc7c5);
  static final mainColor = const Color(0xFF89dAd0);
  static final iconColor1 = const Color(0xFFffd28d);
  static final iconColor2 = const Color(0xFFfcab88);
  static final paraColor = const Color(0xFF8f837f);
  static final buttonBackgroundColorColor = const Color(0xFFf7f6f4);
  static final signColor = const Color(0xFFa9a29f);
  static final titleColor = const Color(0xFF5c524f);
  static final mainBlackColor = const Color(0xFF332d2b);
  static final yellowColor = const Color(0xFFffd379);
  static final Color textColor1 = Color(0xFF989acd);
  static final Color textColor2 = Color(0xFF878593);
  static final Color bigTextColor = Color(0xFF2e2e31);
  static final Color purpleColor = Color(0xFF5d69b3);
  static final Color starColor = Color(0xFFe7bb4e);
  static final Color mainTextColor = Color(0xFFababad);
  static final Color buttonBackground = Color(0xFFf1f1f9);
  static final Color darkGreen = Color(0xff00726d);
  static final Color borderColor = Colors.grey.withOpacity(0.4);
  static final Color appWhite = Color(0xfff5f7f9);
  static final Color appBlack = Colors.black87.withOpacity(0.7);
  static final Color appGreen = Color.fromARGB(-74, 42, 173, 122);
  static const orange = Color(0xFFFC6011);
  static const primary = Color(0xFF4A4B4D);
  static const secondary = Color(0xFF7C7D7E);
  static const placeholder = Color(0xFFB6B7B7);
  static const placeholderBg = Color(0xFFF2F2F2);
  static const kPrimaryColor = Color(0xFF0E4944);
  static const kAccentColor = Color(0xFF9BD35A);
  static const kThirdColor = Color(0xFFDBF4E9);
  static const kForthColor = Color(0xFFB3CDC5);
  static const kBlue = Color(0xFFC5E5F8);
  static const kPlaceholder1 = Color(0xFFD8D8D8);
  static const kPlaceholder2 = Color(0xFFF5F6F8);
  static const kPlaceholder3 = Color(0xFFF4F4F6);
  static const kTextColor1 = Color(0xFFC9C9C9);
  static const kTextColor2 = Color(0xFFDEDEDE);
  static const kTitle = Color(0xFF3B3B3B);
  static const darkOrange = Color(0xFFEC6813);
  static const lightOrange = Color(0xFFf8b89a);
  static const darkGrey = Color(0xFFA6A3A0);
  static const lightGrey = Color(0xFFE5E6E8);
  static const Color nearlyWhite = Color(0xFFFAFAFA);
  static const Color notWhite = Color(0xFFEDF0F2);
  static const Color white = Color(0xFFFFFFFF);
  static const Color gray = Color(0xFF3A5160);
  static const Color nearlyBlack = Color(0xFF213333);
  static const Color nearlyDarkBlue = Color(0xFF2633C5);
  static const Color background = Color(0xFFF2F3F8);
  static const Color darkText = Color(0xFF253840);
  static const Color darkerText = Color(0xFF17262A);
  static const Color lightText = Color(0xFF4A6572);
}